Update devfile.yaml

diff --git a/devfile.yaml b/devfile.yaml
--- a/devfile.yaml
+++ b/devfile.yaml
@@ -30,6 +30,8 @@ components:
       env:
         - name: DEBUG_PORT
           value: '5858'
+        - name: PATH
+          value: "${HOME}/.local/bin:${PATH}"
       endpoints:
         - name: https-node
           targetPort: 3000
@@ -46,13 +48,16 @@ commands:
       # In that case, add `runOn: containerCreation` under `exec`.
       commandLine: >
         sh -c '
+          echo "Creating ~/.local/bin directory..." &&
+          mkdir -p ${HOME}/.local/bin &&
           echo "Downloading and installing oc CLI..." &&
           curl -o oc.tar https://downloads-openshift-console.apps.rm1.0a51.p1.openshiftapps.com/amd64/linux/oc.tar &&
           tar -xvf oc.tar &&
           rm -f oc.tar &&
           chmod +x oc &&
-          mv oc /usr/local/bin/oc &&
-          echo "oc CLI installed at /usr/local/bin/oc"
+          mv oc ${HOME}/.local/bin/oc &&
+          echo "oc CLI installed at ${HOME}/.local/bin/oc" &&
+          oc version || echo "oc installed, but 'oc version' might fail if not connected."
         '
       workingDir: /tmp
       group:
