Update devfile-nodejs.yaml

diff --git a/devfile-nodejs.yaml b/devfile-nodejs.yaml
--- a/devfile-nodejs.yaml
+++ b/devfile-nodejs.yaml
@@ -1,6 +1,6 @@
 schemaVersion: 2.2.2
 metadata:
-  name: nodejs
+  name: nodejs-user18
   displayName: Node.js Runtime
   description: Node.js 18 application
   icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/node-js.svg
@@ -10,7 +10,8 @@ metadata:
     - ubi8
   projectType: Node.js
   language: JavaScript
-  version: 2.2.1
+  version: 0.0.5
+
 starterProjects:
   - name: nodejs-starter
     git:
@@ -18,6 +19,7 @@ starterProjects:
         revision: main
       remotes:
         origin: 'https://github.com/nodeshift-starters/devfile-sample.git'
+
 components:
   - name: runtime
     container:
@@ -35,7 +37,31 @@ components:
         - exposure: none
           name: debug
           targetPort: 5858
+
 commands:
+  - id: install-oc
+    exec:
+      component: runtime
+      # You could also do this during container startup if you'd like it automated right away.
+      # In that case, add `runOn: containerCreation` under `exec`.
+      commandLine: >
+        sh -c '
+          echo "Creating /opt/app-root/bin" &&
+          mkdir /opt/app-root/bin &&
+          echo "Downloading and installing oc CLI..." &&
+          curl -o oc.tar https://downloads-openshift-console.apps.rm1.0a51.p1.openshiftapps.com/amd64/linux/oc.tar &&
+          tar -xvf oc.tar &&
+          rm -f oc.tar &&
+          chmod +x oc &&
+          mv oc /opt/app-root/bin/oc &&
+          echo "oc CLI installed at /opt/app-root/bin/oc" &&
+          oc version || echo "oc installed, but \"oc version\" might fail if not connected."
+        '
+      workingDir: /tmp
+      group:
+        kind: build
+        isDefault: false
+
   - id: install
     exec:
       component: runtime
@@ -44,6 +70,7 @@ commands:
       group:
         kind: build
         isDefault: true
+
   - id: run
     exec:
       component: runtime
@@ -52,6 +79,7 @@ commands:
       group:
         kind: run
         isDefault: true
+
   - id: debug
     exec:
       component: runtime
@@ -60,6 +88,7 @@ commands:
       group:
         kind: debug
         isDefault: true
+
   - id: test
     exec:
       component: runtime
@@ -68,3 +97,6 @@ commands:
       group:
         kind: test
         isDefault: true
+events:
+  postStart:
+    - install-oc
